# Generated by Django 2.0.7 on 2018-07-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movielist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=15)),
                ('runtime', models.CharField(blank=True, max_length=255)),
                ('released', models.CharField(blank=True, max_length=255)),
                ('actors', models.TextField(blank=True)),
                ('season', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movielist'),
        ),
    ]
