# Generated by Django 2.0.7 on 2018-07-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movielist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Year', models.CharField(blank=True, max_length=15)),
                ('Rated', models.CharField(blank=True, max_length=255)),
                ('Released', models.CharField(blank=True, max_length=255)),
                ('Runtime', models.CharField(blank=True, max_length=255)),
                ('Genre', models.CharField(blank=True, max_length=255)),
                ('Director', models.CharField(blank=True, max_length=255)),
                ('Writer', models.CharField(blank=True, max_length=255)),
                ('Actors', models.TextField(blank=True)),
                ('Plot', models.CharField(blank=True, max_length=255)),
                ('Language', models.CharField(blank=True, max_length=255)),
                ('Country', models.CharField(blank=True, max_length=255)),
                ('Awards', models.CharField(blank=True, max_length=255)),
                ('Poster', models.CharField(blank=True, max_length=255)),
                ('Ratings', models.CharField(blank=True, max_length=255)),
                ('Metascore', models.CharField(blank=True, max_length=255)),
                ('imdbRating', models.CharField(blank=True, max_length=255)),
                ('imdbVotes', models.CharField(blank=True, max_length=255)),
                ('imdbID', models.CharField(blank=True, max_length=255)),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('DVD', models.CharField(blank=True, max_length=255)),
                ('BoxOffice', models.CharField(blank=True, max_length=255)),
                ('Production', models.CharField(blank=True, max_length=255)),
                ('Website', models.CharField(blank=True, max_length=255)),
                ('totalSeasons', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movielist'),
        ),
    ]
